name: Assign on "assign me"

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null && contains(github.event.comment.body, 'assign me')
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { issue, comment } = github.context.payload;
            const assignee = comment.user.login;

            await github.rest.issues.addAssignees({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: issue.number,
              assignees: [assignee],
            });
